[bepis] Factorio 14.23 compatibility updates
justjake/chopped pull request #4
Opened 2017-07-25 06:10 UTC by philihp

* Added steps necessary for someone to start up a node on AWS, because nobody wanna run a VM locally.
* Updates to Factorio for newer version, removed old params. Updated params that want .zip on them.
* Added myself.

![](https://media.giphy.com/media/7z5T625EopVle/giphy.gif)

@justjake @sjzhu

2017-07-28 23:01 UTC, justjake requested changes
Seems legit.

Please move the Vagrant stuff to the bottom of the README and retain it! I like vagrant, and it's useful for iterating quickly.

Chef changes good to go.

2017-07-28 23:01 UTC, justjake commented on README.md
> -### Testing chef in Vagrant
I like the vagrant stuff because it lets you provision a new system to test in like 30 secs.

2017-07-30 20:06 UTC, philihp commented
@justjake PTAL

2017-07-30 21:37 UTC, justjake approved these changes

2017-07-30 21:38 UTC, justjake commented
@philihp LGTM

2017-07-30 23:58 UTC, merged